# Generated by Django 2.1 on 2019-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
