# Generated by Django 2.1 on 2019-04-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190402_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='created_time',
            new_name='created',
        ),
    ]
