# Generated by Django 2.1 on 2019-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190402_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='edit',
            field=models.DateField(auto_now=True),
        ),
    ]
