# Generated by Django 2.1 on 2019-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190402_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=500, verbose_name='提问者'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0, verbose_name='问题'),
        ),
    ]
